# Make sure that the neo4j password and username environment variables match for
# both containers.

version: '3'
services:
  web:
    build: .
    environment:
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASS=${NEO4J_PASS:-password}
    ports:
      - "5000:5000"
    depends_on:
      - "db"
  db:
    image: neo4j:3.0
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASS:-password}
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
